# Generated by Django 5.2.7 on 2025-10-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spreadui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("last_keepalive", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
