# Generated by Django 5.0.6 on 2024-06-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, default="", help_text="eg: Robert Menzies", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_name",
            field=models.CharField(
                blank=True, default="", help_text="eg: Bob", max_length=200
            ),
        ),
    ]
